# Site
title:             Hilal 🌙
bio:                'Foodie, self-proclaimed Chef and an avid hip-hop fan. I strive to guide and help others as a software consultant.'
description:        ''
footer:             'Made with 💖 by yours truly'
reading_time:       true
words_per_minute:   200
logo:             https://avatars0.githubusercontent.com/u/3894104?s=450&v=4
locale:             en_US
url:                'hilalh.github.io'
base_url:           'hilalh.github.io'


# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Projects
# projects:
#   - project:
#       name: Bitcoin Book Notes
#       link: http://github.com/hilalh/bitcoinbook-notes
#       icon: https://www.shareicon.net/download/128x128//2015/10/04/111818_send_512x512.png


# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
#twitter:            username
facebook:           hhgotit
github:             hilalh
gitlab:             hilalh
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
instagram:          hhgotit
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
# soundcloud:        hilalh
#weibo:             username
#flickr:            username
#codepen:           username
keybase:           hilalh
#xmpp:              username@server.com
#hackernews:        username

# Gems
# gems:
#   - jekyll-mentions
#   - jekyll-feed
#   - jekyll-sitemap
#   - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Extra Links
# projects_link: 'projects.html
# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
